// items-db-ui-react/src/components/Login.tsx
import React, {FunctionComponent, useState} from 'react';

interface IProps {
  onSignin: (userName: string, pwd: string) => void;
}

export const Login:FunctionComponent<IProps> = ({onSignin}) => {
  const [userName, setUserName] = useState("dan@mycompany.com");
  const [password, setPassword] = useState("123");

  const handleSubmit = (event: React.FormEvent) => {
    event.preventDefault();
    onSignin(userName, password)
  }

  return (

  <form onSubmit={handleSubmit}>
    <div className="form-group">
      <label>User Name:</label>
      <input className="form-control" type="text"  
               value={userName} 
               onChange={(e: React.ChangeEvent<HTMLInputElement>) => setUserName(e.target.value)} />
    </div>
    <div className="form-group">
    <label>Password:
        <input className="form-control" type="text" 
                value={password} 
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setPassword(e.target.value)} />

      </label>
    </div>
    <button type="submit" className="btn btn-primary">Submit</button>
  </form>
  );
}

export default Login;

// items-db-ui-ng/src/app/app/users/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { ItemsApiService } from '../../shared/services/items-api.service';
import { LocalStorageService } from '../../shared/services/localStorage.service';

@Component({
  selector: 'idb-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.sass']
})
export class LoginComponent implements OnInit {

  userName = 'dan@mycompany.com';
  password = '123';
  errorMessage: string;

  constructor(private itemsDataService: ItemsApiService,
              private localStorageService: LocalStorageService) {

  }

  ngOnInit(): void {
  }

  public login = () => {
    console.log(`Attempt log in for ${this.userName} with password ${this.password}`);
    this.itemsDataService.login(this.userName, this.password).subscribe({
      next: result => {
        this.localStorageService.setItem('idb:token', result.token);
        console.log(`token = ${result.token}`);
      },
      error: errMsg => this.errorMessage = errMsg

    });
  }

}

<form (ngSubmit)="login()">
  <div className="form-group" >
    <label>User Name:</label>
    <input [(ngModel)]="userName" name="userName" className="form-control" type="text"
    />
  </div>
  <div className="form-group">
    <label>Password:</label>
    <input [(ngModel)]="password" name="password" className="form-control" type="text"
    />
  </div>
  <button type="submit" className="btn btn-primary">Login</button>
  <button type="button" className="btn btn-primary">Cancel</button>
</form>
